{% set version = "0.2.1" %}

package:
  name: otbenchmark
  version: {{ version }}

source:
  fn: otbenchmark-{{ version }}.tar.gz
  url: https://github.com/openturns/otbenchmark/archive/v{{ version }}.tar.gz
  sha256: 167c4cbcd3a6955ecd959214e1da74d2af8b8e7ccdf6e1ce074081694675113b
  patches:
    # openturns is patched with numpy2 support on conda (but not pip)
    - numpy2.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - python >=3.6
    - openturns >=1.23
    - matplotlib-base >=3

test:
  source_files:
    - tests/
  requires:
    - pip
  commands:
    - pip check
    - python -m unittest discover tests/
  imports:
    - otbenchmark

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: A benchmark library for OpenTURNS

extra:
  recipe-maintainers:
    - jschueller
